import { revalidateTag } from "next/cache";
import { NextRequest, NextResponse } from "next/server";

const LOCALES = ["tr", "en", "ar"];

// Map Strapi model UIDs to the cache tags that should be invalidated
function getTagsForModel(model: string): string[] {
    const tags: string[] = [];

    if (model === "api::product.product") {
        LOCALES.forEach((locale) => {
            tags.push(`homepage:${locale}:featured-products`);
            tags.push(`products:all:${locale}`);
            tags.push(`products:all:${locale}:grid`);
            tags.push(`products:all:${locale}:sizes`);
        });
    }

    if (model === "api::category.category") {
        LOCALES.forEach((locale) => {
            tags.push(`homepage:${locale}:categories`);
            tags.push("navbar-categories");
        });
    }

    // Slug-specific tags are invalidated by the entry data sent from Strapi
    return tags;
}

function getSlugTags(model: string, entry: any): string[] {
    const tags: string[] = [];
    const slug: string | undefined = entry?.slug;
    const documentId: string | undefined = entry?.documentId;

    if (model === "api::product.product") {
        if (slug) {
            LOCALES.forEach((locale) => {
                tags.push(`product:${locale}:${slug}`);
                // slug variants like "slug-en", "slug-ar" generated by the sync
                tags.push(`product:${locale}:${slug}-${locale}`);
            });
        }
        if (documentId) {
            tags.push(`product:${documentId}`);
        }
    }

    if (model === "api::category.category") {
        if (slug) {
            LOCALES.forEach((locale) => {
                tags.push(`category:${locale}:${slug}`);
                tags.push(`products:${locale}:${slug}`);
                tags.push(`products:${locale}:${slug}:grid`);
                tags.push(`products:${locale}:${slug}:sizes`);
            });
        }
    }

    return tags;
}

export async function POST(req: NextRequest) {
    const secret = req.nextUrl.searchParams.get("secret");

    if (secret !== process.env.REVALIDATION_SECRET) {
        return NextResponse.json({ error: "Invalid secret" }, { status: 401 });
    }

    let body: any;
    try {
        body = await req.json();
    } catch {
        return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    const model: string = body?.model ?? "";
    const entry: any = body?.entry ?? {};

    const tags = [...getTagsForModel(model), ...getSlugTags(model, entry)];

    if (tags.length === 0) {
        return NextResponse.json({ revalidated: false, reason: "Unknown model" });
    }

    tags.forEach((tag) => revalidateTag(tag, "default"));

    console.log(`[Revalidate] model=${model} tags=${tags.join(", ")}`);

    return NextResponse.json({ revalidated: true, tags });
}
